# Generated by Django 4.1.3 on 2022-11-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150, verbose_name='Бренд')),
                ('model', models.CharField(max_length=150, verbose_name='Модель')),
                ('color', models.CharField(max_length=150, verbose_name='Цвет')),
                ('made', models.CharField(max_length=150, verbose_name='Сделано')),
                ('price', models.CharField(max_length=250, verbose_name='Цена')),
                ('delivery', models.CharField(max_length=150, verbose_name='Доставка')),
                ('condition', models.CharField(max_length=150, verbose_name='Состояние')),
                ('category', models.CharField(max_length=150, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
    ]
